Add read only load function
vchuravy/GPUifyLoops.jl pull request #102
Opened 2020-01-14 22:43 UTC by lcw

This adds a wrapper for `CUDAnative.ldg` so that we can specify GPU
loads using the read-only texture cache.  Currently the CPU version just
does a regular load.

2020-01-14 22:44 UTC, lcw commented
bors try

2020-01-14 22:45 UTC, lcw commented
cc: @mwarusz

2020-01-19 05:28 UTC, mwarusz requested changes

2020-01-19 05:28 UTC, mwarusz commented on src/read_only_load.jl
> +    @inline function __read_only_load(::CUDA, A::CUDAnative.CuDeviceArray,
```suggestion
    Base.@propagate_inbounds function __read_only_load(::CUDA, A::CUDAnative.CuDeviceArray,
```

2020-01-19 05:28 UTC, mwarusz commented on src/read_only_load.jl
> +@inline __read_only_load(::CPU, A::Array, index::Integer) = A[index]
```suggestion
Base.@propagate_inbounds __read_only_load(::CPU, A::Array, index::Integer) = A[index]
```

2020-01-19 05:28 UTC, mwarusz commented on src/read_only_load.jl
> +@inline read_only_load(A, index) = __read_only_load(backend(), A, index)
```suggestion
Base.@propagate_inbounds read_only_load(A, index) = __read_only_load(backend(), A, index)
```

2020-01-22 21:44 UTC, vchuravy reviewed
LGTM! Looks good to me.

2020-01-22 21:46 UTC, lcw commented
bors try

2020-01-23 01:22 UTC, lcw commented
bors r+

2020-01-23 01:29 UTC, merged